name: Run Model

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'


jobs:
  run-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            data
            model
            network/graphs
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv pip install --system --pre mesa numpy pandas geopandas networkx shapely
      - name: Run model script
        working-directory: model
        run: python model.py
